version: "3.9"
volumes:
  my-volume:
    external: true
networks:
  mt-network:
    driver: bridge    
services:  
  frontend:
    build : .
    container_name: front-end 
    restart: always
    ports:
      - 8085:80
    networks:
      - mt-network
         


