version: "3.9"
volumes:
  my-volume:
    external: true
networks:
  default:
    external:
      name: matching

services:  
  frontend:
    build : .
    container_name: front-end 
    ports:
      - 8089:80
    networks:
      default:
        aliases:
          - frontend
    depends_on:
      - mydb
  mydb:
    image: mysql
    container_name: forumsdb
    ports:
      - 8088:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=forumsdb
    volumes:
      - my-volume:/var/lib/mysql
    networks:
      default:
        aliases:
          - mydb              


